// electron-sdk/src/renderer/App.tsx
import { useEffect, useMemo, useState } from 'react'
import { Feature, useFeatureFlag, useFeatureGate } from '@ops-ai/electron-feature-flags-toggly/react'
import {
  evaluateFeatureGate, flushTelemetry, incrementCounter, isFeatureOn,
  recordUsage, recordView, setGauge,
} from '@ops-ai/electron-feature-flags-toggly'
import {
  buildOrderContext,
  coreFlags,
  filterCapabilities,
  filterFlags,
  filterPreset,
  filterResult,
  type PresetName,
} from './demo-model'

type Flags = Record<string, boolean>

function useLiveFlags(): Flags {
  const [flags, setFlags] = useState<Flags>({})

  useEffect(() => {
    // getFlags is async because it crosses the secure preload boundary. The
    // listener makes the snapshot react to main-process refresh/WebSocket events.
    void window.toggly?.getFlags().then(setFlags).catch(() => setFlags({}))
    return window.toggly?.onFlagsUpdated(setFlags)
  }, [])

  return flags
}

function FlagPill({ name, value }: { name: string; value: boolean | undefined }) {
  return <span className={value ? 'pill on' : 'pill off'}>{name}: {value ? 'ON' : 'OFF'}</span>
}

export function App() {
  const flags = useLiveFlags()
  const [identity, setIdentity] = useState('anonymous')
  const [role, setRole] = useState('user')
  const [preset, setPreset] = useState<PresetName>('matching')
  const [vip, setVip] = useState(true)
  const [notice, setNotice] = useState('Choose a session identity, then apply it to refresh the main-process evaluation context.')
  const [telemetryNotice, setTelemetryNotice] = useState('Telemetry is owned by Electron main.')
  const dashboard = useFeatureFlag('new-dashboard')
  const legacyApi = useFeatureFlag('api-v2', { negate: true })
  const allCore = useFeatureGate(['new-dashboard', 'api-v2'], { requirement: 'all' })
  const anyCore = useFeatureGate(['new-dashboard', 'api-v2'], { requirement: 'any' })
  const order = useMemo(() => buildOrderContext(vip), [vip])
  const expressCheckout = useFeatureFlag('ExpressCheckout', { context: order })
  // Unlike getFlags(), this call carries the selected Order. It therefore
  // exercises the live ContextProperty rule instead of showing its global
  // snapshot, which has no Order.Vip value to evaluate against.
  const contextPropertyFilter = useFeatureFlag('filter-context-property', { context: order })

  const applySession = async (nextIdentity = identity, nextRole = role): Promise<void> => {
    // This call refreshes definitions because identity/claims participate in the
    // evaluated-signed request. It changes the desktop application's singleton
    // context, deliberately only from an explicit user session action.
    await window.toggly?.setContext({ identity: nextIdentity, claims: { role: nextRole } })
    setIdentity(nextIdentity)
    setRole(nextRole)
    setNotice(`Desktop session context applied: ${nextIdentity}, role=${nextRole}.`)
  }

  const applyPreset = async (name: PresetName): Promise<void> => {
    const next = filterPreset(name)
    setPreset(name)
    setVip(next.vip)
    await applySession(next.identity, next.role)
    setNotice(`${name === 'matching' ? 'Matching' : 'Non-matching'} preset applied. Header-derived rows remain unavailable to this SDK bridge.`)
  }

  const clearSession = async (): Promise<void> => {
    await window.toggly?.clearContext()
    setIdentity('anonymous')
    setRole('user')
    setNotice('The SDK generated a new anonymous desktop context and refreshed the flag snapshot.')
  }

  return <main>
    <header>
      <p className="eyebrow">Toggly Electron SDK · secure main → preload → React renderer</p>
      <h1>Feature flags for a desktop app</h1>
      <p>A feature flag is a named decision. Toggly evaluates its rules and this React interface chooses the matching UI branch. A flag is useful for rollout and experiments; it is not authorization.</p>
      <nav>{['home', 'declarative', 'programmatic', 'identity', 'entity', 'filters', 'electron', 'configuration'].map(id => <a key={id} href={`#${id}`}>{id}</a>)}</nav>
    </header>

    {!window.sampleConfiguration.hasAppKey && <aside className="banner"><strong>Missing App Key.</strong> The main process uses safe OFF defaults and makes no definitions request. Copy <code>.env.example</code> to <code>.env.local</code>; the key never enters this renderer bundle.</aside>}

    <section id="home">
      <h2>1. Home: follow one decision</h2>
      <ol><li>The dashboard stores a rule for a flag key such as <code>new-dashboard</code>.</li><li>Main initializes Toggly before it creates this window.</li><li>Preload exposes a narrow bridge; React reads only decisions, never the App Key.</li><li>UI renders the ON or OFF branch below.</li></ol>
      <div className="panel"><h3>First toggle: new-dashboard</h3><p>{dashboard.isEnabled ? 'Dashboard v2 is enabled for this evaluated context.' : 'Classic dashboard is shown because new-dashboard is OFF or uses its safe default.'}</p><Feature featureKey="new-dashboard" loading={<p>Checking the main-process bridge…</p>}><strong className="success" data-testid="offline-feature">New dashboard content</strong></Feature><Feature featureKey="new-dashboard" negate><strong data-testid="offline-negated-feature">Classic dashboard content</strong></Feature><span data-testid="offline-hook" hidden>{String(dashboard.isEnabled)}</span></div>
      <h3>Live snapshot</h3><div className="pills">{[...coreFlags, ...filterFlags].map(key => <FlagPill key={key} name={key} value={flags[key]} />)}</div>
    </section>

    <section id="declarative">
      <h2>2. Declarative React gates</h2>
      <p><code>Feature</code> is a React component from the published SDK. It listens for main-process flag updates and renders its children only when the gate succeeds.</p>
      <div className="grid">
        <div className="panel"><h3>Feature</h3><Feature featureKey="new-dashboard"><p className="success">new-dashboard allowed this content.</p></Feature><p>{dashboard.isEnabled ? 'ON branch' : 'OFF branch'}</p></div>
        <div className="panel"><h3>Negate</h3><p>{legacyApi.isEnabled ? 'Legacy API content shows while api-v2 is OFF.' : 'api-v2 is ON, so the legacy content is hidden.'}</p></div>
        <div className="panel"><h3>Multi-key</h3><p>All: {allCore.isEnabled ? 'ON' : 'OFF'} · Any: {anyCore.isEnabled ? 'ON' : 'OFF'}</p><Feature featureKeys={['new-dashboard', 'api-v2']} requirement="any"><p className="success">At least one dashboard/API decision is enabled.</p></Feature></div>
      </div>
      <p className="caveat"><strong>Variant limitation:</strong> Electron SDK 1.1.0 publishes boolean flags and gates, but no named-variant or experiment-assignment API. Telemetry variants label explicit events; they are not an A/B assignment.</p>
    </section>

    <section id="programmatic">
      <h2>3. Programmatic API</h2>
      <p>Use the renderer helpers when a decision belongs in ordinary application logic. They synchronously call the narrow bridge and fail closed when preload is absent.</p>
      <div className="panel"><p><code>isFeatureOn('enhanced-submit')</code>: <strong>{isFeatureOn('enhanced-submit') ? 'ON' : 'OFF'}</strong></p><p><code>evaluateFeatureGate(['new-dashboard', 'api-v2'], 'any')</code>: <strong>{evaluateFeatureGate(['new-dashboard', 'api-v2'], 'any') ? 'ON' : 'OFF'}</strong></p><p>Keep security decisions on a trusted service: a person can inspect or modify desktop UI, even when a feature gate hides a button.</p></div>
    </section>

    <section id="identity">
      <h2>4. Explicit desktop session identity</h2>
      <p>Unlike a web server, Electron main is a long-lived singleton. The bridge’s <code>setContext</code> changes its current desktop session and triggers a refresh; it is not request-scoped. A production app should derive this from its authenticated account lifecycle, clear it on sign-out, and avoid letting untrusted page input choose an identity.</p>
      <div className="controls"><label>Identity <input value={identity} onChange={event => setIdentity(event.target.value)} /></label><label>Role <select value={role} onChange={event => setRole(event.target.value)}><option value="user">user</option><option value="admin">admin</option></select></label><button onClick={() => void applySession()}>Apply session</button><button onClick={() => void clearSession()}>Clear session</button></div><p className="notice">{notice}</p>
    </section>

    <section id="entity">
      <h2>5. Entity context: Order VIP</h2>
      <p>The <code>ExpressCheckout</code> decision receives an Order only for this evaluation. The SDK recognizes the published <code>{'{ kind, key, attributes }'}</code> entity shape; <code>Vip</code> and optional <code>Total</code> live in its attributes. This avoids changing the desktop identity to test an order.</p>
      <div className="controls"><button onClick={() => setVip(true)}>Use VIP order</button><button onClick={() => setVip(false)}>Use standard order</button><code>{JSON.stringify(order)}</code></div><p>Express checkout: <strong>{expressCheckout.isEnabled ? 'ON — show expedited checkout.' : 'OFF — show standard checkout.'}</strong></p>
    </section>

    <section id="filters">
      <h2>6. Filters matrix</h2>
      <p>The controls send supported identity/claims inputs through the bridge and use the selected Order on the entity call. They intentionally do not claim that a desktop process can create HTTP country, User-Agent, or Accept-Language targeting inputs.</p>
      <div className="controls"><button onClick={() => void applyPreset('matching')}>Apply Matching preset</button><button onClick={() => void applyPreset('non-matching')}>Apply Non-matching preset</button><span>Active: {preset}</span></div>
      <p>Matching: alice / admin / US / English / Chrome on macOS / VIP. Non-matching: bob / user / CA / French / Firefox on Windows / standard Order.</p>
      <table><thead><tr><th>Flag</th><th>Expected input</th><th>Electron 1.0.0</th><th>Live result</th></tr></thead><tbody>{filterCapabilities.map(([key, input, support]) => <tr key={key}><td><code>{key}</code></td><td>{input}</td><td>{support}</td><td>{support === 'Supported' || support === 'Supported per evaluation' ? (filterResult(key, flags, contextPropertyFilter.isEnabled) ? 'ON' : 'OFF') : 'Not evaluated by this bridge'}</td></tr>)}</tbody></table>
      <p className="caveat">Percentage is sticky by identity, so a 50% rollout has no prescribed ON/OFF result. AlwaysOn and an open TimeWindow remain ON when configured. The ContextProperty row evaluates the selected Order; header-derived rows remain visible as setup guidance, but the Electron API does not expose their inputs.</p>
    </section>

    <section id="electron">
      <h2>7. Electron-specific surfaces</h2>
      <div className="grid"><div className="panel"><h3>Main owns configuration</h3><p>It reads <code>TOGGLY_APP_KEY</code>, initializes once before windows, verifies signed definitions when configured, stores last-known-good definitions under Electron <code>userData</code>, and owns refresh/WebSocket work.</p></div><div className="panel"><h3>Preload narrows capability</h3><p><code>exposeToggly()</code> uses contextBridge. Renderer code can ask for flag values, set the explicit session context, and subscribe to updates; it cannot call arbitrary IPC or read the key.</p></div><div className="panel"><h3>Updates fan out</h3><p>The SDK sends a new flag snapshot to every open window after a refresh. React hooks and <code>Feature</code> re-evaluate, keeping UI consistent without exposing transport details.</p></div></div>
      <div className="panel"><h3>Usage and business metrics</h3><p>Checks above are counted by the main-process SDK. These buttons demonstrate explicit events and metrics through the validated preload bridge. Configure <code>TOGGLY_DISABLE_TELEMETRY=true</code> in main to opt out.</p><div className="controls">
        <button onClick={() => { recordUsage('new-dashboard', dashboard.isEnabled ? 'enabled' : 'disabled'); setTelemetryNotice('Recorded dashboard usage.') }}>Record usage</button>
        <button onClick={() => { recordView('Cart', 'blue'); setTelemetryNotice('Recorded Cart view.') }}>Record view</button>
        <button onClick={() => { incrementCounter('orders', 2); setTelemetryNotice('Incremented orders by 2.') }}>Add orders</button>
        <button onClick={() => { setGauge('cartItems', 3); setTelemetryNotice('Set cartItems to 3.') }}>Set cart items</button>
        <button onClick={() => void flushTelemetry().then(() => setTelemetryNotice('Main-process telemetry flush completed.')).catch(() => setTelemetryNotice('Telemetry flush failed.'))}>Flush</button>
      </div><p className="notice">{telemetryNotice}</p></div>
    </section>

    <section id="configuration">
      <h2>8. Configuration and failure behavior</h2>
      <p>{window.sampleConfiguration.hasAppKey ? `A key is configured for ${window.sampleConfiguration.environment}. Initialisation may still use cached/default values if fetch or signature verification fails.` : 'No configured key: this is a deliberate offline/default mode, not a connection error.'}</p><p>Definitions are public configuration for the selected app, but dashboard management credentials are secrets and must never ship. The app key is held in main and the displayed configuration is only a boolean status.</p>
    </section>
  </main>
}

// solidjs-sdk/src/App.tsx
import { createSignal, For, Show, Suspense } from 'solid-js';
import {
  Feature,
  TogglyProvider,
  useFeatureFlag,
  useToggly,
  type TogglyOptions,
} from '@ops-ai/solid-feature-flags-toggly';
import { defaults, keys, order, presets, sections } from './catalog';

function Workshop(props: { configured: boolean }) {
  const toggly = useToggly();
  const [identity, setIdentity] = createSignal('');
  const [vip, setVip] = createSignal(true);
  const [deviceReady, setDeviceReady] = createSignal(true);
  const [result, setResult] = createSignal('Run a check to observe a current result.');
  const [submitted, setSubmitted] = createSignal(false);
  const dashboard = useFeatureFlag('new-dashboard');
  // The entity is supplied at the read boundary; it never changes global identity.
  const checkout = useFeatureFlag('ExpressCheckout', () => order(vip()));
  // A device prerequisite can only narrow a remotely enabled feature.
  toggly.client.setLocalGates([{ id: 'device', flagKeys: ['api-v2'], isEnabled: deviceReady }]);
  const apply = async (matching: boolean) => {
    const preset = presets[matching ? 'Matching' : 'Non-matching'];
    setIdentity(preset.identity);
    setVip(matching);
    await toggly.client.setContext(preset);
  };
  return (
    <main>
      <header>
        <p class="eyebrow">Toggly × SolidJS</p>
        <h1>Feature flag workshop</h1>
        <p>Trace a flag from configuration to a reactive UI branch.</p>
      </header>
      <Show when={!props.configured}>
        <aside role="status">
          No app key configured. Offline defaults are active; remote targeting and entity conditions
          require your Toggly application.
        </aside>
      </Show>
      <nav aria-label="Workshop sections">
        <For each={sections}>{(name, index) => <a href={`#section-${index()}`}>{name}</a>}</For>
      </nav>
      <section id="section-0">
        <h2>1. Home</h2>
        <p>
          A key names a feature; an environment supplies its definitions. Initialization fetches
          signed evaluated definitions and accessors read the resulting snapshot.
        </p>
        <p>
          First toggle: enable <code>new-dashboard</code> in Production, then refresh. “New
          dashboard” appears; disabling it shows “Classic dashboard”. Without a key, the documented
          default stays on.
        </p>
        <button onClick={() => toggly.client.refresh()} disabled={toggly.loading()}>
          Refresh definitions
        </button>
        <p aria-live="polite">
          {toggly.loading() ? 'Refreshing…' : 'Snapshot available'} {toggly.error()?.message}
        </p>
        <details>
          <summary>Application flag checklist</summary>
          <ul>
            <For each={keys}>
              {(key) => (
                <li>
                  <code>{key}</code>
                </li>
              )}
            </For>
          </ul>
        </details>
        <pre aria-label="Live snapshot">{JSON.stringify(toggly.flags(), null, 2)}</pre>
      </section>
      <section id="section-1">
        <h2>2. Declarative gates</h2>
        <Feature feature="new-dashboard" loading={<p>Loading dashboard…</p>}>
          <p>New dashboard</p>
        </Feature>
        <Feature feature="new-dashboard" negate>
          <p>Classic dashboard</p>
        </Feature>
        <Feature feature={['new-dashboard', 'api-v2']} requirement="all">
          <p>Both dashboard and API v2 are enabled.</p>
        </Feature>
        <Feature feature={['new-dashboard', 'api-v2']} requirement="all" negate>
          <p>The all gate is closed.</p>
        </Feature>
        <Feature feature={['new-dashboard', 'beta-access']} requirement="any">
          <p>At least one feature is enabled.</p>
        </Feature>
        <p>
          Boolean alternative:{' '}
          <strong>{dashboard() ? 'New experience' : 'Classic experience'}</strong>. This is not a
          variant assignment; this SDK exposes no experiment assignment API.
        </p>
      </section>
      <section id="section-2">
        <h2>3. Programmatic API</h2>
        <button onClick={() => setResult(`new-dashboard: ${toggly.evaluate(['new-dashboard'])}`)}>
          Evaluate dashboard
        </button>
        <output>{result()}</output>
        <h3>Telemetry exercise</h3>
        <p>Usage and view are explicit actions; rendering this workshop does not record a view.</p>
        <button onClick={() => toggly.recordUsage('new-dashboard', 'sample-control')}>
          Record usage
        </button>
        <button onClick={() => toggly.recordView('new-dashboard')}>Record view</button>
        <button onClick={() => toggly.incrementCounter('orders', 2)}>Add orders</button>
        <button onClick={() => toggly.setGauge('active-carts', 3)}>Set active carts</button>
        <button onClick={() => void toggly.flushTelemetry()}>Flush telemetry</button>
        <button
          onClick={() => {
            if (toggly.evaluate(['enhanced-submit'])) setSubmitted(true);
          }}
          disabled={!toggly.evaluate(['enhanced-submit'])}
        >
          Try enhanced submit
        </button>
        <p>
          {submitted() ? 'Local demonstration submitted.' : 'No submission yet.'} A production
          server must authorize its own operation.
        </p>
      </section>
      <section id="section-3">
        <h2>4. Identity</h2>
        <p>
          Targeting belongs to this provider. Changing identity clears prior results immediately.
          Demo claims are not authentication.
        </p>
        <label>
          Identity{' '}
          <input value={identity()} onInput={(event) => setIdentity(event.currentTarget.value)} />
        </label>
        <button onClick={() => toggly.client.setContext({ identity: identity() })}>
          Apply identity
        </button>
        <button
          onClick={() => {
            setIdentity('');
            void toggly.client.setContext({ identity: '', groups: [], claims: {} });
          }}
        >
          Clear identity, groups and claims
        </button>
        <button onClick={() => apply(true)}>Matching preset</button>
        <button onClick={() => apply(false)}>Non-matching preset</button>
        <p>
          Matching uses alice / staff / role=admin; Non-matching uses bob / no groups / role=user.
        </p>
      </section>
      <section id="section-4">
        <h2>5. Entity context</h2>
        <label>
          <input
            type="checkbox"
            checked={vip()}
            onChange={(event) => setVip(event.currentTarget.checked)}
          />
          VIP order
        </label>
        <pre>{JSON.stringify(order(vip()), null, 2)}</pre>
        <p>ExpressCheckout: {String(checkout())}</p>
        <Feature feature="ExpressCheckout" entity={order(vip())}>
          <p>Express checkout for this VIP order</p>
        </Feature>
        <Feature feature="ExpressCheckout" entity={order(vip())} negate>
          <p>Standard checkout</p>
        </Feature>
        <p>
          Bind ExpressCheckout to Order and configure Vip = true. Missing entity definitions fail
          closed; no-key defaults do not simulate these conditions.
        </p>
      </section>
      <section id="section-5">
        <h2>6. Filters matrix</h2>
        <p>
          Apply the presets above, then inspect each real result. Percentage is sticky by identity,
          so neither preset promises a particular percentage result. Country, browser, language,
          device and OS use your actual request; these controls cannot spoof browser headers.
        </p>
        <table>
          <thead>
            <tr>
              <th>Flag</th>
              <th>Current result</th>
              <th>Input source</th>
            </tr>
          </thead>
          <tbody>
            <For each={keys.filter((key) => key.startsWith('filter-'))}>
              {(key) => (
                <tr>
                  <td>{key}</td>
                  <td>{String(toggly.evaluate([key], 'all', false, order(vip())))}</td>
                  <td>
                    {key === 'filter-context-property'
                      ? 'Order.Vip'
                      : ['filter-targeting', 'filter-user-claims', 'filter-percentage'].includes(
                            key,
                          )
                        ? 'Identity / claims'
                        : 'Service rule and actual browser request'}
                  </td>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </section>
      <section id="section-6">
        <h2>7. Solid ownership</h2>
        <p>
          Native accessors update consumers when results change. Provider disposal aborts pending
          fetches, clears timers, and closes WebSockets. Gate branches are lazy and preserve Solid
          ownership.
        </p>
        <label>
          <input
            type="checkbox"
            checked={deviceReady()}
            onChange={(event) => {
              setDeviceReady(event.currentTarget.checked);
              toggly.client.notifyLocalGatesChanged();
            }}
          />
          Device ready for API v2
        </label>
        <Feature feature="api-v2">
          <p>API v2 ready.</p>
        </Feature>
        <Feature feature="api-v2" negate>
          <p>API v2 held by remote or local gate.</p>
        </Feature>
        <Suspense fallback={<p>Initial resource loading…</p>}>
          <ResourceView />
        </Suspense>
        <p>
          The resource observes initialization; the live snapshot above observes later refreshes.
          This browser sample makes no SolidStart SSR claim.
        </p>
      </section>
      <section id="section-7">
        <h2>8. Configuration</h2>
        <p>
          {props.configured
            ? 'Live browser application configured.'
            : 'Missing VITE_TOGGLY_APP_KEY: copy .env.example to .env and set your application key.'}
        </p>
        <p>
          VITE_ variables are public and substituted during the Vite build. Use Production and allow
          http://localhost:5173 in Toggly. Restart the dev server after editing .env.
        </p>
        <p>
          Signatures are verified by default. Network failures retain same-session data or defaults;
          errors are visible above. This sample stores verified signed definitions and their public
          key in localStorage. After an online refresh, the same targeting can restore definitions
          without service access; the page assets must still be available.
        </p>
      </section>
    </main>
  );
}
function ResourceView() {
  const toggly = useToggly();
  return <p>Initial resource keys: {Object.keys(toggly.resource() ?? {}).length}</p>;
}
export default function App(props: { config?: TogglyOptions } = {}) {
  // Only browser application identifiers belong in VITE_ variables, never secrets.
  const config = props.config ?? {
    appKey: import.meta.env.VITE_TOGGLY_APP_KEY || undefined,
    environment: import.meta.env.VITE_TOGGLY_ENVIRONMENT || 'Production',
    enableTelemetry: import.meta.env.VITE_TOGGLY_ENABLE_TELEMETRY !== 'false',
    metricsBaseUrl: import.meta.env.VITE_TOGGLY_METRICS_BASE_URL || undefined,
    flagDefaults: defaults,
    // Callbacks defer origin-owned storage access; the SDK handles denied access.
    storage: {
      getItem: (key: string) => window.localStorage.getItem(key),
      setItem: (key: string, value: string) => window.localStorage.setItem(key, value),
    },
  };
  return (
    <TogglyProvider config={config}>
      <Workshop configured={Boolean(config.appKey)} />
    </TogglyProvider>
  );
}
